### PR TITLE
More bigdata

### PR DESCRIPTION
**Pull request by hellowin**
Add more big data questions :+1:

### CODE REVIEW

**Comment by pixelastic** [comment]
Haha, thanks and glad you liked it :)

The original descriptions had some tongue in cheek in them, do you think you could rewrite the new descriptions in that spirit?

**Comment by hellowin** [comment]
Hahaha... it's ok, I'll try to rewrite them later. Please correct my english btw, I'm sucks in English :stuck_out_tongue:

**Comment by paul42** [comment]
grammar looks good from here :+1:

**Comment by pixelastic** [comment]
@hellowin I'll leave this PR open a few days to give you some time to think of something funny to add :)

**Comment by hellowin** [comment]
How about this one? I reduce the questions. Try to add more later :smile:

**Comment by pixelastic** [comment]
@paul42 @jaredpetersen : Would you mind having a look at the blurbs submitted by @hellowin and post any possible fix to the grammar?

**Comment by pixelastic** [comment]
Thanks @hellowin, I just merged your PR.

**Pull request merged**
