### PR TITLE
grammar tweaks for questions.js

### PR DESCRIPTION
**Pull request by paul42**
A few tense and plurality changes for english language

### CODE REVIEW

**Comment by paul42** [comment]
English speaker, but with my horrible typing you probably can't tell.

**Comment by pixelastic** [comment]
Haha. I see you're commiting like crazy. I'll give you a little more time before accepting the PR (just in case you have other fixes to push).

Thanks for the PR!

**Comment by jaredpetersen** [comment]
The last commit (20b7bddcef372c8b6bea0df22a6e886cccdb3168) still has a capitalization error in the second sentence of the blurb.

**Comment by pixelastic** [comment]
Thanks to both of you. I'll merge this one and patch the capital letter.

**Comment by jaredpetersen** [comment]
There are also a few mistakes that have been missed (corrections in bold):
- Crebase: "Crebase has the highest defense of all ice-type pokemon. Do no**t** confuse with HBase, Couchbase, MeshBase, Graphbase or KirbyBase."
- Feebas: "Feebas require**s** Swift Swim to get the marvel scale."
- Etc.

**Comment by jaredpetersen** [comment]
Also, not related to this issue - The blurb about Feebas doesn't make any sense within the context of the game.

**Comment by pixelastic** [comment]
@jaredpetersen Thanks. I've fixed the grammar. Feel free to suggest a new blurb for Feebas.

**Pull request merged**
