### PR TITLE
Added Ambari, Geode and Geodude

### PR DESCRIPTION
**Pull request by uploadWizdom**

### CODE REVIEW

**Comment by pixelastic** [comment]
Pretty funny, thanks! :)

**Comment by uploadWizdom** [comment]
I've ducked up a couple of things: the commas, the grammar and the geodude extension for the picture.

**Comment by uploadWizdom** [comment]
It's geodude.jpg not geodude.png, please can you update it. Cheers

**Comment by pixelastic** [comment]
I fixed the commas and a few typos already. Just fixed the image right now

**Pull request merged**
